function test_joystick_buttons()
	result = joysticks[1]:isGamepadDown("a")
	love.graphics.print(tostring(result), 200, 20)
	result = joysticks[1]:isGamepadDown("b")
	love.graphics.print(tostring(result), 200, 40)
	result = joysticks[1]:isGamepadDown("x")
	love.graphics.print(tostring(result), 200, 60)
	result = joysticks[1]:isGamepadDown("y")
	love.graphics.print(tostring(result), 200, 80)
	result = joysticks[1]:isGamepadDown("back")
	love.graphics.print(tostring(result), 200, 100)
	result = joysticks[1]:isGamepadDown("guide")
	love.graphics.print(tostring(result), 200, 120)
	result = joysticks[1]:isGamepadDown("start")
	love.graphics.print(tostring(result), 200, 140)
	result = joysticks[1]:isGamepadDown("leftstick")
	love.graphics.print(tostring(result), 200, 160)
	result = joysticks[1]:isGamepadDown("rightstick")
	love.graphics.print(tostring(result), 200, 180)
	result = joysticks[1]:isGamepadDown("leftshoulder")
	love.graphics.print(tostring(result), 200, 200)
	result = joysticks[1]:isGamepadDown("rightshoulder")
	love.graphics.print(tostring(result), 200, 220)
	result = joysticks[1]:isGamepadDown("dpup")
	love.graphics.print(tostring(result), 200, 240)
	result = joysticks[1]:isGamepadDown("dpdown")
	love.graphics.print(tostring(result), 200, 260)
	result = joysticks[1]:isGamepadDown("dpleft")
	love.graphics.print(tostring(result), 200, 280)
	result = joysticks[1]:isGamepadDown("dpright")
	love.graphics.print(tostring(result), 200, 300)
end
	